config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:new, :create]
  root to: 'visitors#new'
end

app/models/contact.rb
 class Contact
  include ActiveModel::Model
  attr_accessor :name, :string
  attr_accessor :email, :string
  attr_accessor :content, :string
  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :content
  validates_format_of :email,
    with: /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
  validates_length_of :content, :maximum => 500
end

app/models/owner.rb
class Owner

  def name
    name = 'Griffin The Intern'
  end

  def birthdate
    birthdate = Date.new(1997, 7, 8)
  end

  def countdown
    today = Date.today
    birthday = Date.new(today.year, birthdate.month, birthdate.day)
    if birthday > today
      countdown = (birthday - today).to_i
    else
      countdown = (birthday.next_year - today).to_i
    end
  end

  def ucsfcount
    firstday = Date.new(2016, 6, 20)
    today = Date.today
    ucsfcount = (today - firstday).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
end
  def create
    @contact = Contact.new(secure_params)
    if @contact.valid?
      # TODO send message
      flash[:notice] = "Message sent from #{@contact.name}."
      redirect_to root_path
else
      render :new
    end
end
private
  def secure_params
    params.require(:contact).permit(:name, :email, :content)
end end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def new
    @owner = Owner.new
end end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<% content_for :title do %>Contact<% end %> 
<h3>Contact</h3>
<p> If you submit a valid contact form it will appear on the home page! </p>
<div class="form">
	<%= simple_form_for @contact do |form| %>
		<%= form.error_notification %>
		<%= form.input :name, autofocus: true %>
		<%= form.input :email %>
		<%= form.input :content, as: :text %>
		<%= form.button :submit, 'Submit', class: 'submit' %>
	 <% end %>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li> 
<li><%= link_to 'Mission', page_path('mission') %></li> 
<li><%= link_to 'Contact', new_contact_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Learn Rails" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Learn Rails" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About Griffin The Intern</h3>
<p> Griffin is a sophomore at UCLA School of Engineering. </p>
<p> He enjoys the simple things in life: taking notes, getting coffee and other intern activities. </p>
<img src="/Griff.jpg" alt="Portrait" style="width:250px;height:300px;">

app/views/pages/contact.html.erb
<% content_for :title do %>Contact<% end %> <h3>Contact</h3>

app/views/pages/mission.html.erb
<% content_for :title do %>mission<% end %>
<img src="/summer.jpg" alt="Portrait" style="width:500px;height:300px;">
<h3>Mission</h3>
<p> This app was built from scratch to mimic the functions of a rails composer starter appication in order to learn the basics of the framework. </p>

app/views/pages/new.html.erb
<% content_for :title do %>Contact<% end %> <h3>Contact</h3>
<div class="form">
<%= simple_form_for :contact, url: contact_path do |form| %> <%= form.input :name, autofocus: true %>
<%= form.input :email %>
<%= form.input :content, as: :text %>
<%= form.button :submit, 'Submit', class: 'submit' %> <% end %>
</div>

app/views/visitors/new.html.erb
<h3>Home</h3>
<p>Welcome to the home of <%= @owner.name %>.</p>
<p>I was born on <%= @owner.birthdate %>.</p>
<p>Only <%= @owner.countdown %> days until my birthday!</p>
<p>I have worked at UCSF for <%= @owner.ucsfcount %> Days.</p>
<img src="/intern.jpg" alt="Portrait" style="width:400px;height:300px;">